controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omnibot:
      type: omni_wheel_controller/OmniWheelController

omnibot:
  ros__parameters:
    omni_wheel_names: ['wheel0_joint', 'wheel1_joint', 'wheel2_joint']
    omni_wheel_angle: [1.0471976, 3.141592, -1.0471976]
    omni_wheel_direction: [-1.0, -1.0, -1.0]

    omni_wheel_distance: 0.13889
    # we account for the reduction ratio (1:8) by dividing
    # actual wheel radius (0.064702 m) by 8
    # wheel_radius: 0.00808775
    wheel_radius: 0.064702


    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    enable_odom_tf: true

    cmd_vel_timeout: 3.0
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 3.0
    linear.x.min_acceleration: -3.0
    linear.x.max_jerk: 0.5
    linear.x.min_jerk: -0.5

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 3.14159265
    angular.z.min_velocity: -3.14159265
    angular.z.max_acceleration: 9.42477796076938
    angular.z.min_acceleration: -9.42477796076938
    angular.z.max_jerk: 0.5
    angular.z.min_jerk: -0.5